### ISSUE TITLE
Conflicting bower dependencies when installing alongside px-iconography-design

### ISSUE THREAD

**Issue by colinjlacy** [PredixDev/px-mobile-design#1]
## Expected behavior and actual behavior:

I get a bower dependency conflict when I pull this package in alongside `px-iconography-design`.  According to the version finder (lifesaver that, BTW), I should target `^1.0.0` of both.  

![screen shot 2018-01-16 at 9 24 36 am](https://user-images.githubusercontent.com/4993605/34996391-1ed814bc-fa9f-11e7-8900-417e60d949ea.png)

I would expect that following the version finder would ensure smooth bower installations. 
However this package pulls in `^0.3.0` of `px-iconography-design`, and therefore causes a conflict.  https://github.com/PredixDev/px-mobile-design/blob/master/bower.json#L48

![screen shot 2018-01-16 at 9 11 02 am](https://user-images.githubusercontent.com/4993605/34996468-57419292-fa9f-11e7-885d-2a8e0f40011a.png)

I know that I can (and did) add a resolution to my bower.json, but I figured this should be logged since it directly conflicts with the guide, and would probably cause problems for anyone who includes both packages.

**Comment by randyaskin** [comment]
This one should probably be marked as deprecated in the version finder - it was only used by `table-view`, `drawer` and `navbar` which are all deprecated.

**Comment by colinjlacy** [comment]
Ok, sounds like I can remove it from my bower.json then
